### ISSUE TITLE
push with ffmpeg and pull from server

### ISSUE THREAD

**Issue by NacerFaraj** [harlanc/xiu#108]
I need to use ffmpeg to read packets from IP cameras and publish it using a media server. I read packets with RTSP, and have to publish it with RTSP. For example, I want to write packets to rtsp://localhost:8554/[camera-ip], and read it form that point. 

Is there any manual to read and understand how to publish to xiu media server? using [mediamtx](https://github.com/bluenviron/mediamtx) it is very clear and straightforward. I want to examine the performance of xiu as well.

**Comment by harlanc** [comment]
@NacerFaraj 

Using ffmpeg to pull RTSP stream of ip camera and push to other RTSP server(like xiu), you can use the following command:

    ffmpeg -i rtsp://camera_ip:port/stream_name -c:v copy -c:a copy  rtsp://xiu_server_ip:port/stream_name

I'm not very familiar with the steps of mediamtx on how to transfer RTSP stream..

**Comment by NacerFaraj** [comment]
Thank you. The instruction is  the same with the one provided in [mediamtx](https://github.com/bluenviron/mediamtx).
