### ISSUE TITLE
随便问下，支持 rtsp 吗？

### ISSUE THREAD

**Issue by Jiuyong** [harlanc/xiu#11]
不是太懂视频流媒体方面，但是 cv 好像只能读 rtsp 协议，我知道为什么。或者支持这个协议是不是有什么困难？菜鸟懵问，见笑勿喷。

**Comment by harlanc** [comment]
cv是啥？目前还不支持rtsp，支持的话得写代码开发

**Comment by Jiuyong** [comment]
CV，计算视觉，有时候也是对 OpenCV 的简称。
因为用 OpenCV 的时候他只支持这种流媒体协议，所以碰到视频处理就尴尬了。
就是因为不是搞视频方面，所以才不知道为啥没有 rtsp 协议，但是为啥 OpenCV 又只支持读取这个协议啊，所以很懵逼。
要是有自己实现这个协议的能力，就不会问得这么傻了不是。

**Comment by harlanc** [comment]
RTSP好像在监控方面用的比较多吧，现在还没有时间搞这个协议，以后有时间了可以考虑

**Comment by Jiuyong** [comment]
就是为了获取视频源来分析。

**Comment by harlanc** [comment]
难点就在协议本身，把收发流的各个细节搞清楚，就比较好弄

**Comment by Jiuyong** [comment]
原来如此，果然是骨头。真是辛苦你们了！
