### ISSUE TITLE
静态回源是否支持多个源节点

### ISSUE THREAD

**Issue by l0g1n** [harlanc/xiu#112]
我的使用场景比较奇葩，推流多，播放少。
搭建多个源节点，使用Haproxy来负载，用于分散在线的流，而播放时，则走边缘节点，或者是直接走源节点

**Comment by harlanc** [comment]
边缘如何知道哪个源有流？这种场景比较适合动态回源吧

**Comment by l0g1n** [comment]
> 边缘如何知道哪个源有流？这种场景比较适合动态回源吧，需求列表里有人提到，就是通过调用接口获取正确的源地址，不过这个功能还没有实现

好的，感谢回复，会持续关注的，谢谢
