### ISSUE TITLE
HLS Server returned 404 Not Found

### ISSUE THREAD

**Issue by xuchao-ovo** [harlanc/xiu#123]
rtsp转hls 
ffplay -i http://localhost:8081/live/test/test.m3u8
访问not found，发现目录下并没有生成live/test切片文件夹
![image](https://github.com/harlanc/xiu/assets/35905622/03fd1c6d-adeb-4acd-b758-7f927307a8c2)
![image](https://github.com/harlanc/xiu/assets/35905622/5c3c44ba-2922-412f-96be-8609e14b16e4)

**Comment by xuchao-ovo** [comment]
![image](https://github.com/harlanc/xiu/assets/35905622/32e8a952-b8ef-4efa-9768-a04f31ef9ce6)

**Comment by harlanc** [comment]
把RTMP的端口也打开一下吧，现在RTSP转HLS走下面的流程:

      RTSP -> RTMP -> HLS

**Comment by xuchao-ovo** [comment]
可以了 感谢感谢
