### ISSUE TITLE
rtsp转hls访问hls跨域问题

### ISSUE THREAD

**Issue by xuchao-ovo** [harlanc/xiu#124]
![image](https://github.com/harlanc/xiu/assets/35905622/f7022c0e-1f1e-49cd-8d30-d74ec969e9ff)

**Comment by harlanc** [comment]
Try the branch https://github.com/harlanc/xiu/tree/fix_cors to see if it can solve the problem.

**Comment by xuchao-ovo** [comment]
可以推指定 ip 的rtsp的视频流么，比如 rtsp://admin:root123456@192.168.1.1:554/Streaming/Channels/001

**Comment by irg1008** [comment]
Shouldn't this be in the main branch?? I just can't connec tiwht HLS on the frontend

**Comment by muhammad-towfique-imam** [comment]
@harlanc do you have any plans to add config properties to disable CORS?
