### ISSUE TITLE
Support RTMP to WebRTC

### ISSUE THREAD

**Issue by danielboros1990** [harlanc/xiu#128]
Hi there,

is it possible to support RTMP to WebRTC?

**Comment by harlanc** [comment]
It can be supported, but not implemented yet..

**Comment by dancixx** [comment]
Very helpful issue to play webrtc on ios device if this feature will be supported in the future: https://github.com/suzp1984/srs/commit/edfd318987f101d1fd0f81d1529c680b2203b394
