### ISSUE TITLE
直接读取rtsp流连接进行转码

### ISSUE THREAD

**Issue by xuchao-ovo** [harlanc/xiu#129]
不用推流工具可以直接读取rtsp流连接进行转码么
![image](https://github.com/harlanc/xiu/assets/35905622/8e33f80a-bd6b-41fb-b421-b9346d9d2626)
不用ffmpeg进行推流，直接读取rtsp://admin:root123456@192.168.1.62:554/Streaming/Channels/001，怎么实现

**Comment by harlanc** [comment]
目前还不支持
