### ISSUE TITLE
支持自动拉rtsp流吗？

### ISSUE THREAD

**Issue by kid-ai** [harlanc/xiu#136]
我看给的例子都是给服务推流

**Comment by harlanc** [comment]
https://www.rustxiu.com/zh-cn/docs/scenarios/rtsp/#%E6%92%AD%E6%94%BE

**Comment by xgene** [comment]
这个不是使用ffmpeg将流推到xiu，再用ffplay播放吗？ 我说的是用xiu拉rtsp流，用ffplay播放。

**Comment by xgene** [comment]
@harlanc

**Comment by harlanc** [comment]
目前还不支持

**Comment by xgene** [comment]
***@***.***的真实姓名,否则被丢弃.

**Comment by harlanc** [comment]
https://github.com/harlanc/xiu/pull/144 现在可以拉RTSP流了

**Comment by xgene** [comment]
***@***.***的真实姓名,否则被丢弃.
