### ISSUE TITLE
我希望用xiu将海康NVR的RTSP转成HLS流如何配置

### ISSUE THREAD

**Issue by wcpsoft** [harlanc/xiu#138]
类似源地址rtsp://admin:122@192.168.1.18:554/Streaming/Channels/101

目前我的配置文件是
[rtsp]
enabled = true
port = 445

[rtsp.auth]
pull_enabled = true
push_enabled = true
algorithm = "simple"

[httpflv]
enabled = true
port = 8081

[httpflv.auth]
pull_enabled = true
algorithm = "simple"

[log]
level = "info"

[log.file]
enabled = false
rotate = "hour"
path = "./logs"

[authsecret]
key = "admin"
password = "testAy2024"

[[streams.sources]]
url = "rtsp://admin:122@192.168.1.18:554/Streaming/Channels/101"
app = "live"
name = "stream"

**Comment by harlanc** [comment]
目前xiu只能接受RTSP推流，海康可以把RTSP流推到server端吗？

**Comment by wcpsoft** [comment]
> 目前xiu只能接受RTSP推流，海康可以把RTSP流推到server端吗？

可以GB28181协议推流

**Comment by harlanc** [comment]
#live server configu/rations
    ##########################
    #   RTMP configurations  #
    ##########################
    [rtmp]
    enabled =  true 
    port = 1935
    gop_num = 0
    [rtmp.auth]
    pull_enabled = false
    push_enabled = false
    # simple or md5
    algorithm = "simple"
    
    
    [httpnotify]
    enabled = false
    on_publish = "http://localhost:3001/on_publish"
    on_unpublish = "http://localhost:3001/on_unpuslish"
    on_play = "http://localhost:3001/on_play"
    on_stop = "http://localhost:3001/on_stop"
    
    [authsecret]
    # used for md5 authentication
    key = "123"
    # used for simple authentication
    password = "123"
    
    
    [httpapi]
    port = 8001
    
    ##########################
    #    RTSP configurations  #
    ##########################
    [rtsp]
    enabled = true
    port = 5545
    relay_enabled = true
    [rtsp.auth]
    pull_enabled = false
    push_enabled = false
    # simple or md5
    algorithm = "simple"
    
    
    
    ##########################
    #    HLS configurations  #
    ##########################
    [hls]
    enabled = true
    port = 8080
    need_record = true
    [hls.auth]
    pull_enabled = false 
    # simple or md5
    algorithm = "simple"
    
    
    ##########################
    #   LOG configurations   #
    ##########################
    [log]
    level = "info"
    [log.file]
    # write log to file or not（Writing logs to file or console cannot be satisfied at the same time）.
    enabled = false
    rotate = "hour" #[day,hour,minute]
    path = "/app/logs"

添加了拉取camera RTSP流到本地的功能，使用上面的配置可以转成HLS，使用说明 https://github.com/harlanc/xiu/pull/144
