### ISSUE TITLE
HLS server returns 404

### ISSUE THREAD

**Issue by partap** [harlanc/xiu#15]
I've tried configuring xiu, following the first sample in the readme.

After publishing a stream using ffmeg, I can connect to the rtmp and httpflv streams using ffplay with no problem, but I cannot play back the hls stream..the server only returns 404.

I've tried to connect to `http://localhost:8080/live/test/test.m3u8`, as indicated in documentation...

And then, in case there was a typo in the readme, I also tried:
`http://localhost:8080/live/test/playlist.m3u8` (wowza-style url)
`http://localhost:8080/live/test.m3u8` (similar to httpflv url)

All urls return 404 from the xiu server.

I'm unfamiliar with rust, so I figured before I go digging into the code to see if I can find if there is an alternate url format that works, I should ask here...or see if there are any known issues with the hls server.

Thanks,
-Partap

**Comment by partap** [comment]
Oh...OK.
I read through the main HLS server file (protocol/hls/src/server.rs)... 
it appears that it's trying to serve up actual files from the fs... e.g.  "./live/test/test.m3u8"
...which don't exist.

I can't tell yet if this means the server is supposed to be dynamically generating these files from the incoming rtmp stream elsewhere and it's not working, or if the HLS server functionality is just incomplete...

**Comment by harlanc** [comment]
Thanks for your report,could you let me see your    contents of configuration file? And what's your running OS？

-Harlan

**Comment by Aslan2142** [comment]
I'm experiencing the same exact issue

**Comment by harlanc** [comment]
@partap @Aslan2142  I fixed it in xiu v0.0.8, just try again^_^
