### ISSUE TITLE
Is the HLS output stream "live" or cached?

### ISSUE THREAD

**Issue by raptpz** [harlanc/xiu#18]
It seems that HLS chunks are cached in a local folder, so in some conditions it may happen to reproduce "old" content .  
How is managed the local cache (.ts chunks) and "m3u8" index file with "live" / real time streams ? 

Thank you very much,

**Comment by harlanc** [comment]
The TS list will keep the latest 6 ones(now is hardcoded), and the old ones will be deleted automatically, the m3u8 file is generated according to the dynamic TS list.

In the future release , XIU will support to configure the values in the configuration file.

**Comment by raptpz** [comment]
Thank you very much for explanation, I check with a live stream source and the behaviour is correct.
Yes, that feature sounds nice: it will also permit to optimize latency for HLS output stream.
