### ISSUE TITLE
HLS VOD support? 

### ISSUE THREAD

**Issue by KudryavtsevDmitry** [harlanc/xiu#21]
Hello. I have several questions about features

Does it support HLS VOD? If so, does it make it on-the-fly packaging (without writing/storing chunks on disk)
Does it support mp4, mp3 containers?

**Comment by harlanc** [comment]
It supports HLS now and the m3u8/ts files are stored on the disk. The mp3/mp4 containers are not supported.

**Comment by KudryavtsevDmitry** [comment]
Thanks for quick answer!
