### ISSUE TITLE
请问 这个要怎么用？

### ISSUE THREAD

**Issue by hearsay316** [harlanc/xiu#3]
如题，这个要怎么用？

**Comment by harlanc** [comment]
目前还在开发阶段，功能还不完善。目前支持的功能：

- 支持OBS推Rtmp流

- 支持ffplay播放Rtmp流。（其它播放器没测过）


如何用：

可以自己按照readme编译一个debug版本出来，目前测试过的平台有macOS和centos7

**Comment by harlanc** [comment]
@hearsay316 功能基本都写完了，可以按照文档装一下，试试看吧
