### ISSUE TITLE
Stream statistics

### ISSUE THREAD

**Issue by datagutt** [harlanc/xiu#33]
Would be nice to be able to get information/stats about the streams that are currently published:
Video/audio codec, bitrate, resolution, bytes sent/received, fps

Something similar to this:
https://github.com/illuspas/Node-Media-Server#streams-stats

It would be nice to have this as an HTTP endpoint, but any way of getting it programatically would be OK as well.

**Comment by harlanc** [comment]
Hi @datagutt  
   The audio/video statistic information can be queried now using HTTP api, you can try the new feature and make some suggestions if you wish..
