### ISSUE TITLE
how to play a video file？

### ISSUE THREAD

**Issue by zzxap** [harlanc/xiu#45]
how do this?
 open 
https://www.xxx.com/xiu?file=xxx.mp4  
then 
play the xxx.mp4  ?

**Comment by harlanc** [comment]
No, xiu cannot use a mp4 file as input or output.

**Comment by zzxap** [comment]
how to play http://xxx.com/playlist.m3u8

**Comment by harlanc** [comment]
Please follow the steps from README.

**Comment by ta3pks** [comment]
m3u8 is hls playlist file you cna play it natively on safari or you can use hls.js or some player that uses hls.js under the hood to play it https://vimejs.com/?ref=madewithsvelte.com is one such player @zzxap
