### ISSUE TITLE
Recording is supported?

### ISSUE THREAD

**Issue by danielboros1990** [harlanc/xiu#48]
Is it possible to record the rtmp streaming?

**Comment by harlanc** [comment]
Currently not supported, but it's easily achievable.

**Comment by danielboros1990** [comment]
Great, thank you. We would like to use Xiu instead of Nginx, this would be pretty nice if the recording would be supported.

**Comment by harlanc** [comment]
Now the RTMP stream can be saved as HLS files, you need to do the following configurations:
     
    [hls]
    # true or false to enable or disable the feature
    enabled = true
    # listening port
    port = 8080
    # need record the live stream or not
    need_record = true

Then when RTMP stream is published to xiu, it will remux the stream to HLS and the ts files will not be deleted when the stream is unpublished, and a VOD m3u8 will also be generated in the same folder with ts files in the end.
