### ISSUE TITLE
执行make local或者make online报错

### ISSUE THREAD

**Issue by ytlm** [harlanc/xiu#56]
![image](https://github.com/harlanc/xiu/assets/11896584/06db935d-5b2a-42fd-93b3-fece725556ac)
![image](https://github.com/harlanc/xiu/assets/11896584/09e52554-0efd-4820-ae0d-a95881ab13ca)
![image](https://github.com/harlanc/xiu/assets/11896584/4900850f-8c48-4409-ad8f-f5e320cedef0)
## 重新修改update_project_conf.sh可以正常运行
![image](https://github.com/harlanc/xiu/assets/11896584/a9f3b9df-07d4-4df3-8866-2939b5d1b0c4)
![image](https://github.com/harlanc/xiu/assets/11896584/bee21a31-23b5-443d-a00b-804c37b73ea6)

**Comment by harlanc** [comment]
谢谢指出问题，可能用的shell不一样吧，我在 mac和centos上试了下 "==" 和 “=” 都可以，你可能用的是 dash：
[https://stackoverflow.com/questions/44604637/unexpected-operator-error-in-shell-script](https://stackoverflow.com/questions/44604637/unexpected-operator-error-in-shell-script)

如果可以，提交个PR吧
