### ISSUE TITLE
RTMP 推送设备断电后，超时逻辑未能正确执行

### ISSUE THREAD

**Issue by ningnao** [harlanc/xiu#67]
**XIU version**
master(65c8defcea9858c1aee6920e9f85affb645596c6)

**Describe the bug**
RTMP 推送设备断电后，超时逻辑未能正确执行

排查了一下原因，设备断电后程序阻塞在了这行代码
```rust
// library/bytesio/src/bytesio.rs:159
158  async fn read(&mut self) -> Result<BytesMut, BytesIOError> {
159          let message = self.stream.next().await;  <- 阻塞在这行代码
160  
161          match message {
162              Some(data) => match data {
...
```

因此在`read_timeout()`方法中的超时逻辑未能正确执行，当设备恢复重连的时候，旧链接未被关闭，出现以下错误
```
2023-10-26T02:40:36Z ERROR streamhub] event_loop Publish err: exists
```

另外在`read_timeout()`方法中处理超时逻辑会将`read()`方法中的异常信息覆盖掉，这在排查问题的过程中造成了一定的困扰

**Comment by ningnao** [comment]
我尝试对这个问题进行修复并提交了PR，不知道这样处理是否妥当

**Comment by harlanc** [comment]
这个函数之前改过一版，https://github.com/harlanc/xiu/commit/5eed9a43101e5676e04f36cf5048f47cf598e45e， 记不太清楚问题是如何复现的了，但看来是有问题的，我这边也再好好测测。

**Comment by ningnao** [comment]
我了这版代码，read_timeout方法中对超时的处理似乎没有问题，但在read_parse_chunks方法中实际调用的read方法，并没有调用read_timeout，我想这应该是出现问题的原因

**Comment by harlanc** [comment]
嗯嗯，有可能，昨天测试了两种case，这里也记录一下：

1. ffmpeg 推RTMP流到xiu，非正常退出（kill杀死进程）
2. OBS推流(MAC)，非正常退出（Mac的强制退出）

self.stream.next().await 这句话没有pending，而是直接返回了None
