### ISSUE TITLE
播放hls协议的视频, 视频位置放在哪里? 

### ISSUE THREAD

**Issue by suveng** [harlanc/xiu#88]
`ffplay -i http://localhost:8080/live/test/test.m3u8`
readme中写道, `/live/test/test.m3u8`中的文件应该存放在哪里? 

使用信息
- mac 使用cargo install 安装 xiu
 
配置
<img width="631" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/455e6af8-bbc2-48b1-9563-2177f4fc021c">
xiu启动成功截图
<img width="566" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/625b34dc-627c-4162-a05f-5ec50728db52">
xiu的bin文件和视屏文件在同一目录下
<img width="753" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/6999053b-eb53-4ee2-876e-fe80cce16fa3">
ffplay调用结果截图
<img width="581" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/7142edef-9dcb-45fd-894b-2fc98ee8a74f">

**Comment by suveng** [comment]
<img width="759" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/69806b3e-f4c7-4165-bb42-b902ca4b529b">

**Comment by suveng** [comment]
1. 先push视屏到xiu
<img width="588" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/c322232b-e8fc-42bb-9fdf-26c38e36189f">
2. ffplay 测试是否可以查看
3. 使用js框架 hls.js, 快速集成查看vime的https://vimejs.com/components/providers/hls
4. 最后效果
<img width="1920" alt="image" src="https://github.com/harlanc/xiu/assets/30512096/d954cc83-a092-4098-b257-48d571932fb3">

**Comment by suveng** [comment]
还有一个问题, 上面评论的步骤是推送和订阅, 但是我想直接xiu使用本地文件返回一个视屏, 现在不知道怎么使用

**Comment by harlanc** [comment]
如果推流地址是 rtmp://127.0.0.1:1935/live/t3 
对应的hls 拉流地址是： http://127.0.0.1:8080/live/t3/t3.m3u8 

xiu直接读取本地文件，然后发布一个直播流的方式目前还不支持
