### ISSUE TITLE
Stream RTSP directly from xiu

### ISSUE THREAD

**Issue by thewh1teagle** [harlanc/xiu#93]
Can I stream rtsp directly from xiu by passing `path` to video file?
Or alternatively, use ffmpeg to read frames and push them into `xiu` via `stdin`?

The goa:
I want to simplify the server starting.

**Comment by thewh1teagle** [comment]
@harlanc 
Do you think it's useful feature? compared to simply using loopback network as now?

**Comment by harlanc** [comment]
I'm not entirely sure in what scenarios this feature is used, but it definitely brings convenience to you. However, I apologize as I am only maintaining this project in my spare time, which is limited. So, I want to focus my time on developing the most basic and common functionalities. You can implement this feature yourself, which shouldn't be too difficult. You can parse a file to obtain audio and video frame data, publish it to StreamHub, and subscribe to the RTSP event to receive the audio and video frames for distribution to the player. If you need any further assistance, feel free to continue the conversation.
