### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by svenstaro** [harlanc/xiu#95]
OBS supports sending a bearer token. I think it'd be nice if that were supported by xiu for some basic authentication.

**Comment by harlanc** [comment]
What authentication method do you usually use?

**Comment by svenstaro** [comment]
I think OBS uses `Bearer`? To be honest, I'm not super sure which authentication they support but I think it might make sense to support the same scheme.

**Comment by mpisat** [comment]
Whip supports Bearer: HTTP header authorization. However, it would be nice if xiu supports both Bearer and auth based on a parameter such as whip?app=live&stream=test&key=whateverencryptedpasswordhere

**Comment by harlanc** [comment]
To implement the feature, some refactor work needs to be done: most of the http mod codes in RTSP and WebRTC library are duplicate, which can be extracted as a common library and then the authentication logics can be added in this library.

**Comment by harlanc** [comment]
Reference : https://pengrl.com/lal/#/auth for the auth algorithms.

**Comment by svenstaro** [comment]
Thanks!

**Comment by harlanc** [comment]
https://harlanc.github.io/v0.10.0/docs/authentication/introduction Doc for Authentication Algorithms.
