### ISSUE TITLE
RtmpUrlParser not working

### ISSUE THREAD

**Issue by zuiyu1998** [harlanc/xiu#96]
**XIU version**
v0.9.1

**Describe the bug**
rtmp url parse fail.     

**To Reproduce**
obs use rtmp://domain.name.cn:1935/live/test?auth_key=test_Key.

**Expected behavior**
app_name: live
stream_name: test

now:
app_name: live/test
stream_name:

**Comment by harlanc** [comment]
If the PUSH URL is rtmp://domain.name.cn:1935/live/test?auth_key=test_Key , you should input as follows:

<img width="974" alt="image" src="https://github.com/harlanc/xiu/assets/10411078/8fe8e636-e861-4b1c-a448-eb2881d88588">

**Comment by zuiyu1998** [comment]
yes.
